import Head from "next/head"
import fs from "fs"
import matter from "gray-matter"
import Link from "next/link"

export default function Home({ events }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          {events.map(({ slug, frontmatter }) => (
            <div key={slug}>
              <Link href={`/events/${slug}`}>{frontmatter.title}</Link>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const files = fs.readdirSync("content/events")

  const events = files.map((fileName) => {
    const slug = fileName.replace(".md", "")
    const readFile = fs.readFileSync(`content/events/${fileName}`, "utf-8")
    const { data: frontmatter } = matter(readFile)

    return {
      slug,
      frontmatter,
    }
  })

  return {
    props: {
      events,
    },
  }
}
